name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-14
    environment: default
    steps:
      - uses: actions/checkout@v3
      - name: SwiftFormat version
        run: swiftformat --version
      - name: Format lint
        run: swiftformat --lint .
      - name: SwiftLint version
        run: swiftlint --version
      - name: Lint
        run: swiftlint lint --quiet
  macos-test:
    runs-on: macos-14
    environment: default
    strategy:
      matrix:
        xcode: ['14.3.1', '15.2']
        # Swift: 5.8.1  , 5.9.2
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/secret-swiftPackageTests.xctest/Contents/MacOS/secret-swiftPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
  linux-test:
    runs-on: ubuntu-latest
    environment: default
    
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: swift test --parallel
